### ISSUE TITLE
it's not done right...

### ISSUE THREAD

**Issue by jimmywarting** [minhducsun2002/leb128#1]
> "LEB128 numbers, done right"

no... your source code depend on NodeJS buffer which is not good for Browser or Deno.... it brings in a hole lot of dependency

**Comment by minhducsun2002** [comment]
Yeah, you're right. When I wrote this almost 3 years ago I didn't know typed arrays existed. :sweat_smile: 

Migrated to `Uint8Array` in 5b3d3cc25ded1e7ae3664a465f93c0fd697ae448. Please re-open the issue if I did something wrong (again). Thanks.

**Comment by jimmywarting** [comment]
thanks
